# Generated by Django 2.0 on 2018-04-13 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180328_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_text', models.CharField(max_length=100)),
                ('error_time', models.DateTimeField(default=datetime.datetime(2018, 4, 13, 9, 18, 17, 523501, tzinfo=utc))),
            ],
        ),
    ]
