# Generated by Django 2.0 on 2018-04-13 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180413_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogging',
            name='error_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='errorlogging',
            name='error_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 9, 47, 46, 922039, tzinfo=utc)),
        ),
    ]
