# Generated by Django 2.0 on 2018-04-22 09:39

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180422_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogging',
            name='error_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 12, 39, 45, 817447)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True, validators=[accounts.models.validate_telephone]),
        ),
    ]
